package Project1Game.core;

public enum EntityType {
    WALL, WATER, SOIL,

    // Cây gốc (6 cây)
    WHEAT, RADISH, CABBAGE, LETTUCE, TOMATO, CORN,

    // 9 cây mới
    GRAPE, CUCUMBER, PEPPER, CAULIFLOWER, BEAN, PINEAPPLE, SUNFLOWER, COCONUT, APPLE,

    PLAYER, SELECTOR, COLLISION, INTERACTION, FIELD,
    NPC, GUIDER, TRADER, DOOR, SLEEP, TRADER_IN, GUIDER_IN,
    ANIMAL, MONSTER
}
