package Project1Game.core;

public enum EntityType {
    WALL, WATER, SOIL, WHEAT, RADISH, CABBAGE, LETTUCE, TOMATO, CORN,
    PLAYER, SELECTOR, COLLISION, INTERACTION, FIELD, NPC, GUIDER, TRADER, DOOR, SLEEP, TRADER_IN, GUIDER_IN, ANIMAL, MONSTER
    }
